name: UI Tests

on:
  pull_request:
    branches: [master]
    paths:
      - 'packages/ui/**'

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        test_number: [1]

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          sparse-checkout: |
            packages

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:ci
        working-directory: ./packages/ui
      - name: Upload coverage artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ui-coverage
          path: ./packages/ui/coverage/lcov.info
          retention-days: 1

  coveralls:
    needs: test
    if: ${{ always() && needs.test.result == 'success' }}
    continue-on-error: true
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ui-coverage
          path: ./coverage
      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          flag-name: ui-tests
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          base-path: './packages/ui'
